### ISSUE TITLE
[Collector] Missing information in Log

### ISSUE THREAD

**Issue by mhaenggi** [exense/djigger#52]
- In the collector log file I can see the JMX connection attempts. But not for all of the configured collectors. 
- Sometimes there are no logs at all. ex. see attached log at 2016-04-21 11:42:02.
- Fatal Exceptions at connection time are not logged in the collector log file but into the stdout. I would expect to have these error logs in the collector log.
  found in version: 1.4.1
  [logging_issues.zip](https://github.com/denkbar/djigger/files/238069/logging_issues.zip)

**Comment by dcransac** [comment]
@jeromecomte can you please take this in account as part of the rework of the logging strategy (see for example issue #44)?

How verbose do we want to be in the collector log? Can we manage those details via logback.xml as well?

**Comment by jeromecomte** [comment]
I'll take this into account and reroute all the collector logs to the logger with the correct log-level.

**Comment by dcransac** [comment]
The problem here is actually a case of misinterpretation of the log entries caused by the following ambiguous message "Creating JMX connection to H51AT20:18102".

It seems this message is logged out prior to **attempting** to connect to the JVM and is therefore logged out one time for each target JVM at the **beginning** and then at the time of each **retry** attempt when the target JVM goes down.

Here's my suggestion to fix this issue

Change the term "Creating" to "Attempting to create" **or** get rid of that message entirely, and just replace it by a "Successful connection" and "Unsuccessful connection" attempt messages at a later point in the code, once we know what the outcome was

**Comment by dcransac** [comment]
In addition, I'd suggest adding the following error and warning handling mechanisms (this might belong to a different issue though) :

- Log ERROR messages and the cause of the error when a connection attempt fails (Credentials denied, Destination Unreachable, etc)
- Log WARNING messages when a connection works but we suspect something is wrong with it (for example multiple definitions with the same server/port combination with the same credentials)

**Comment by david-stephan** [comment]
Improved logging for more clarity, will be available in next release (1.10.3 )
